In [1]:
import numpy as np

In [31]:
# vector
a = np.array([1, 5, 2])
b = np.array([10, 10, 10])
# matrix
c = np.array([[1, 2, 5], [5, 2, 1]])

print(a)
print(b)
print(c)

# Add value to every element of vector
print(a + 1)
# Subtract value from every element of vector
print(a - 1)

# Multiply every element
print(a * 2)
# Divide every element
print(a / 2)

# Multiply elementwise
print(a * b)

# Multiply elementwise matrix
print(a * c)

# Matrix multiplication
print("c * 2 = ", c * 2)

[1 5 2]
[10 10 10]
[[1 2 5]
 [5 2 1]]
[2 6 3]
[0 4 1]
[ 2 10  4]
[0.5 2.5 1. ]
[10 50 20]
[[ 1 10 10]
 [ 5 10  2]]
c * 2 =  [[ 2  4 10]
 [10  4  2]]


In [16]:
# 2x4 (2 rows 4 columns) matrix of zeros
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# 2x4 (2 rows 4 columns) matrix of random value between 0 and 1
np.random.rand(2, 4)

array([[0.13644732, 0.08654052, 0.04459521, 0.34541024],
       [0.74062298, 0.7495844 , 0.53883939, 0.89250857]])

In [37]:
a = np.zeros((1, 4))
b = np.zeros((4, 3))

c = a.dot(b)
print(c)

[[0. 0. 0.]]


In [52]:
a = np.zeros((2, 4))
a[0][0] = 5
b = np.zeros((4, 2))
b[0][0] = 2
b[0][1] = 1
c = a.dot(b)
print(c)

[[10.  5.]
 [ 0.  0.]]


In [56]:
a = np.zeros((1, 2))
b = np.zeros((2, 1))
c = a.dot(b)
print(c)

[[0.]]


In [59]:
a = np.zeros((5, 4)).T
b = np.zeros((5, 6))
c = a.dot(b)
print(c)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
